### PR TITLE
Add cpu exception metric

### PR DESCRIPTION
**Pull request by OrlaM**
Adding the cpu-exception metric to the firefox-ios-health dashboard.

### CODE REVIEW

**Comment by OrlaM** [comment]
@edugfilho I'm finally getting around to adding some more metrics to this thing. Let me know if this looks correct. I don't have access to GCP to run in the test environment to verify. 🙏

**Comment by edugfilho** [comment]
This looks good to me!

**Comment by edugfilho** [comment]
Auto approve / Auto approve PR if no metrics definitions changed (pull_request) failed with 
```
POST /repos/mozilla/metric-hub/pulls/400/reviews - 403 in 153ms
RequestError [HttpError]: Resource not accessible by integration```

@scholtzan do you know what's happening here?

**Comment by scholtzan** [comment]
It's coming from a fork, so a review by a human is required

**Review by scholtzan — APPROVED** [review]

**Comment by edugfilho** [comment]
thank you!

**Pull request merged**
