### PR TITLE
Add a networking off-main-thread outcome

### PR DESCRIPTION
**Pull request by acreskeyMoz**
This outcome examines omt-specific networking performance probes

### CODE REVIEW

**Comment by acreskeyMoz** [comment]
This is my first time making use of glean `timing_distributions`.
I'm not sure if this is valid
```
select_expression = '{{agg_histogram_mean("metrics.timing_distribution.http_content_onstart_delay")}}'
```

**Comment by mikewilli** [comment]
It looks like you're missing the `metrics` data_source definition, which is why the `validate-jetstream` CI check is failing. I also tagged @danielkberry to help with reviewing the metric definitions.

**Comment by acreskeyMoz** [comment]
Thanks.

I'm looking into some other glam probes and I'm pretty sure that my data extraction isn't correct.
So I'm expecting to need to also update the `select_expression`.

**Comment by mikewilli** [comment]
Are we still interested in updating and merging this outcome or can this PR be closed?

**Comment by acreskeyMoz** [comment]
Oh, no longer needed!

**Pull request closed without merging**
