### PR TITLE
add new profile retention outcomes

### PR DESCRIPTION
**Pull request by irrationalagent**
This adds the new profile retention outcomes that we have agreed upon for the desktop funnel:

* repeat first month user: whether the client was DAU at least once sometime between their 2-28th days.
* retained week 4 user: whether the client was DAU at least once in their fourth week (days 22-28).

### CODE REVIEW

**Comment by irrationalagent** [comment]
Don't know why I'm getting `Braced constructors are not supported` from the validate-metrics job

**Review by bani — APPROVED** [review]

**Comment by irrationalagent** [comment]
I'm getting a different error on the validate job now, I tried adding a CLS datasource to the desktop config but that didn't help.

**Comment by irrationalagent** [comment]
@scholtzan do you have any idea why CI is failing here?

**Comment by scholtzan** [comment]
The branch was out of date, CI is now succeeding

**Pull request merged**
