### PR TITLE
Update stricter_pbm.toml

### PR DESCRIPTION
**Pull request by danielkberry**

### CODE REVIEW

**Comment by danielkberry** [comment]
@scholtzan Just to confirm the new behavior: live experiments will use the old definition of this outcome, unless manually triggered? To get a completed experiment to use this new outcome, can I simply rerun the analysis for that experiment?

**Comment by scholtzan** [comment]
You'd either need to add the `--recreate-enrollments` option or run `jetstream rerun-skip --experiment_slug=<slug>` first before doing `rerun`

**Comment by danielkberry** [comment]
ohh, hmm. That's unfortunate, as I didn't do those.

**Comment by scholtzan** [comment]
ah wait, `rerun` alone should be enough

**Pull request merged**
