### PR TITLE
Add `is_default_browser`, `is_default_pdf_handler`, and `is_pinned` F…

### PR DESCRIPTION
**Pull request by ncalexan**
…irefox Desktop metrics.

### CODE REVIEW

**Comment by ncalexan** [comment]
I cribbed these from @danielkberry and extended to the default PDF handler, see https://github.com/mozilla/jetstream-config/pull/249.

**Review by danielkberry — APPROVED** [review]
Default browser and pinned to taskbar LGTM. I'm not very familiar with the pdf handler telemetry, but this seems reasonable? @irrationalagent  may know more. I will say: is there any place that default pdf handler status is aggregated to the (client, day) level? Scanning the main ping table can be expensive...

**Comment by ncalexan** [comment]
> Default browser and pinned to taskbar LGTM. I'm not very familiar with the pdf handler telemetry, but this seems reasonable? @irrationalagent may know more.

I'm not aware of anybody who's done anything with this besides myself and Romain; see, for example, https://sql.telemetry.mozilla.org/queries/86197/source?p_channel=release.  (That's where I got this snippet from.)

> I will say: is there any place that default pdf handler status is aggregated to the (client, day) level? Scanning the main ping table can be expensive...

I looked, but I'm not aware of any such place.  Definitely it's not aggregated into `telemetry.clients_daily` or similar.  Since  the PDF outcome is not default, this seems reasonable.

**Comment by ncalexan** [comment]
@danielkberry I don't have write access so could you merge when you're satisfied?  Thanks!

**Comment by danielkberry** [comment]
Cool, thanks for looking into those comments.

**Pull request merged**
